development:
  sessions:
    default:
      database: imminence_development
      hosts:
        - localhost:27017
      options:
        write:
          w: 1
        read: primary

test:
  sessions:
    default:
      database: imminence_test
      hosts:
        - localhost:27017
      options:
        write:
          w: 1
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
