defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults
  namespace: imminence-development

test:
  <<: *defaults
  namespace: imminence-test

production:
  host: redis-2.backend
  port: 6379
  namespace: imminence
